baseURL = "https://tokuma09.github.io/"
languageCode = "ja"
theme = "anatole"
enableEmoji = true

[params]
title = "人力知恵袋"
author = "Tokuma Suzuki"
description = "データ分析者見習い。勉強したことやとりとめのないことをメモ。"
profilePicture = "/images/tokupooh.jpg"
mainSections = ["blog"]
contentratio = 0.8
copyright = "2022-{{ YEAR }}"
readMore = true
favicon = "favicons/"
doNotLoadAnimations = false
gtagId = "G-REEV38QRJL"
customCss =["css/custom-font.css"]



[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/tokuma09"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/tokutokupooh"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/tokuma-suzuki/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:torutoru.cloud@gmail.com"

[params.math]
enable = true
use = "katex"

## Menu items
[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 1
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 2
  identifier = "blog"
  url = "/blog/"


[taxonomies]
tag = "tags"
